name: linter-checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linter checks
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: pip install -e .
    - name: Install packages needed for tests
      run: pip install pyright flake8
    - name: Run linter checks
      run: flake8 --config ../.flake8 && pyright
