name: Tests with cov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: pip install .
    - name: Install pytest and pytest-cov
      run: pip install pytest pytest-cov
    - name: Run tests and collect coverage
      run: pytest --cov . --cov-report=xml --cov-report=term tests/
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        file: ./coverage.xml
        flags: unittests